# Generated by Django 2.0.2 on 2018-04-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_auto_20180415_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('user', 'name')},
        ),
    ]
