# Generated by Django 2.0.2 on 2018-04-16 12:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_auto_20180416_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
