# Generated by Django 2.0.2 on 2018-04-18 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='user',
        ),
        migrations.AddField(
            model_name='publication',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='backoffice.Campaign'),
            preserve_default=False,
        ),
    ]
