# Generated by Django 2.0.2 on 2018-04-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_auto_20180418_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='name',
            field=models.CharField(default='None', max_length=150, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
