# Generated by Django 2.0.2 on 2018-04-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_publication_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField(verbose_name='Timestamp')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='backoffice.Product')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_video', to='backoffice.Publication')),
            ],
        ),
    ]
