# Generated by Django 2.0.2 on 2018-04-19 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_tagvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='miwouser',
            name='favorite_influencers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
