# Generated by Django 2.0.2 on 2018-04-20 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0013_auto_20180420_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='miwouser',
            name='favorite_tags_video',
            field=models.ManyToManyField(to='backoffice.TagVideo'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 14, 59, 28, 972713, tzinfo=utc), verbose_name='Expiration date'),
        ),
    ]
