# Generated by Django 2.0.2 on 2018-04-23 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_auto_20180420_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 7, 20, 21, 313609, tzinfo=utc), verbose_name='Expiration date'),
        ),
    ]
