# Generated by Django 2.0.2 on 2018-04-23 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_auto_20180423_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='number',
        ),
        migrations.AddField(
            model_name='device',
            name='chanid',
            field=models.CharField(default='', max_length=100, verbose_name='Chan id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 9, 8, 49, 457399, tzinfo=utc), verbose_name='Expiration date'),
        ),
    ]
