# Generated by Django 2.0.2 on 2018-04-23 10:02

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_auto_20180423_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miwouser',
            name='favorite_influencers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 10, 2, 1, 927112, tzinfo=utc), verbose_name='Expiration date'),
        ),
    ]
