# Generated by Django 2.0.2 on 2018-04-23 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0019_auto_20180423_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='public_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Company name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kind',
            field=models.CharField(choices=[('F', 'Follower'), ('I', 'Influencer'), ('A', 'Agency'), ('P', 'Platform')], default='F', max_length=1, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 19, 16, 1, 289205, tzinfo=utc), verbose_name='Expiration date'),
        ),
    ]
