# Generated by Django 2.0.2 on 2018-04-23 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0020_auto_20180423_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kind',
            field=models.CharField(blank=True, choices=[('I', 'Influencer'), ('A', 'Agency'), ('P', 'Platform')], max_length=1, null=True, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 20, 26, 44, 234858, tzinfo=utc), verbose_name='Expiration date'),
        ),
    ]
