# Generated by Django 2.0.2 on 2018-04-24 08:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0021_auto_20180423_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 8, 0, 27, 258877, tzinfo=utc), verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title'),
        ),
    ]
