# Generated by Django 2.0.2 on 2018-04-24 09:35

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0023_auto_20180424_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2018, 5, 1, 9, 35, 47, 442642, tzinfo=utc), verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 1, 9, 35, 47, 444121, tzinfo=utc), verbose_name='Expiration date'),
        ),
    ]
