# Generated by Django 2.0.2 on 2018-04-27 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0025_auto_20180424_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='backoffice.Profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 14, 51, 1, 416391, tzinfo=utc), verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 14, 51, 1, 417931, tzinfo=utc), verbose_name='Expiration date'),
        ),
    ]
