# Generated by Django 2.0.2 on 2018-05-15 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0027_auto_20180504_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='referal_link',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Referal link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 22, 20, 36, 1, 154310, tzinfo=utc), verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 22, 20, 36, 1, 155902, tzinfo=utc), verbose_name='Expiration date'),
        ),
    ]
