# Generated by Django 2.0.2 on 2018-05-21 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0028_auto_20180515_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='product',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 14, 21, 21, 646557, tzinfo=utc), verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 14, 21, 21, 648663, tzinfo=utc), verbose_name='Expiration date'),
        ),
    ]
