# Generated by Django 2.0.2 on 2018-06-28 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0030_auto_20180604_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='referal_action',
            field=models.CharField(choices=[('buy', 'I buy'), ('book', 'I book'), ('down', 'I download')], default='buy', max_length=4, verbose_name='Referal action'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 5, 16, 11, 17, 766426, tzinfo=utc), verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 5, 16, 11, 17, 767541, tzinfo=utc), verbose_name='Expiration date'),
        ),
    ]
